name: Deploy Web App - Backend

on:
  push:
    branches:
      - main  # O la rama que utilizas para la producci√≥n
    paths:
      - 'api/**'
      - '.github/workflows/deploy-backend.yaml'

jobs:
  webserver-1:
    runs-on: 18244  # Etiqueta de tu runner auto-hospedado
    steps:
      - uses: actions/checkout@v3
      
      # The second step sets up Node.js with version 20.
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - name: Install Dependencies
        run: npm install
      
      - name: Run the scripts
        run: |
          echo "Kill all the running PM2 actions"
          pm2 kill 

          echo "Jump to app folder"
          cd /api

          echo "Install app dependencies"
          rm -rf node_modules package-lock.json
          npm install

          echo "Build your app"
          npm run build

          echo "Run new PM2 action"
          NODE_PORT=4000 pm2 start -i 0 index.js --name moneytrackerapi
  
  webserver-2:
    runs-on: 18271  # Etiqueta de tu runner auto-hospedado
    steps:
      - uses: actions/checkout@v3
      
      # The second step sets up Node.js with version 16.
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - name: Install Dependencies
        run: npm install

      - name: Run the scripts
        run: |
          echo "Kill all the running PM2 actions"
          pm2 kill 

          echo "Jump to app folder"
          cd /api

          echo "Install app dependencies"
          rm -rf node_modules package-lock.json
          npm install

          echo "Build your app"
          npm run build

          echo "Run new PM2 action"
          NODE_PORT=4000 pm2 start -i 0 index.js --name moneytrackerapi